version: 0.2

phases:
  pre_build:
    commands:
       - echo Logging / auth in to Amazon ECR
       - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 039612845006.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - echo Building the docker image
      - docker build -t ecs-ecr-project-v1 .
      - docker tag ecs-ecr-project-v1:latest 039612845006.dkr.ecr.ap-south-1.amazonaws.com/ecs-ecr-project-v1:latest


  post_build:
    commands:
     - echo build completed
     - echo pushing in to docker ECR...
     - docker push 039612845006.dkr.ecr.ap-south-1.amazonaws.com/ecs-ecr-project-v1:latest
     - echo Writing image definition file..
     - printf '[{"name":"%s","imageUri":"%s"}]' "" "" > imagedefinitions.json


artifacts:
  files:
    - imagedefinitions.json
